### ISSUE TITLE
Plugin for darkrift 2

### ISSUE THREAD

**Issue by SithWookie** [JamJar00/DarkRift-MySQLConnector#4]
are there any plans to update the plugin for darkrift 2? It compiles fine but I get the following when i add the plugin to my Darkright server. Or am I missing something else?

D:\Projects\Darkrift server>DarkRift.Server.Console.exe
[Error]   PluginFactory         Failed to load one or more plugins from DLL file 'Plugins/MySQLConnector.dll', see trace for exception and more info. Rebuilding plugin may help.
                                 System.Reflection.ReflectionTypeLoadException: Unable to load one or more of the requested types. Retrieve the LoaderExceptions property for more information.
                                    at System.Reflection.RuntimeModule.GetTypes(RuntimeModule module)
                                    at System.Reflection.Assembly.GetTypes()
                                    at DarkRift.Server.PluginFactory.AddFile(String file)

Unhandled Exception: System.NullReferenceException: Object reference not set to an instance of an object.
   at DarkRift.Server.PluginFactory.AddFile(String file)
   at DarkRift.Server.PluginFactory.AddFiles(IEnumerable`1 files)
   at DarkRift.Server.PluginFactory.AddDirectory(String directory, Boolean create)
   at DarkRift.Server.PluginFactory.AddFromSettings(PluginSearchSettings settings)
   at DarkRift.Server.DarkRiftServer..ctor(ServerSpawnData spawnData)
   at DarkRift.Server.Console.Program.Main(String[] args)

**Comment by JamJar00** [comment]
Hi SithWookie,

DarkRift 2 doesn't provide any support for database connectors as it was decided it's out of scope and an unnecessary abstraction from what you can already do with ADO.NET or the connectors provided by the DB developers.

Perhaps mwage's [boilerplate code](https://github.com/mwage/DarkRift2_Boilerplate/tree/master/Plugins/MySQLConnector )can help you?

Jamie
